
### get user with id
GET http://localhost:3000/users/4

###
POST http://localhost:3000/users/signup
Content-Type:application/json

{
    "email":"4@gmail.com",
    "password":"2@gmail.com"
}

###
POST http://localhost:3000/users/signin
Content-Type:application/json

{
    "email":"4@gmail.com",
    "password":"2@gmail.com"
}

###
GET http://localhost:3000/users/me
Content-Type:application/json


###
GET http://localhost:3000/users/signout
Content-Type:application/json


### get all users
GET http://localhost:3000/users

### remove user by id
DELETE http://localhost:3000/users/3


###
PATCH http://localhost:3000/users/3
Content-Type:application/json

{
    "password":"3@gmail.com"
}
